### ISSUE TITLE
Can't connect to ArcGIS

### ISSUE THREAD

**Issue by ivanoblomov** [Spark-Bio/covid-storepoint#69]
## Description
Master is [failing on CI](https://github.com/Spark-Bio/covid-storepoint/runs/644987566?check_suite_focus=true) because ArcGIS is returning null. Here's what ArcGIS' `geoservices` gem itself returns:
```ruby
irb(main):003:0> require 'geoservices.rb'
=> true
irb(main):004:0> service = Geoservice::MapService.new(url: "https://services.arcgis.com/8ZpVMShClf8U8dae/ArcGIS/rest/services/TestingLocation
_public/FeatureServer")
irb(main):005:0> data = service.query(0)
irb(main):006:0> data
=> nil
```

## Steps to Reproduce

1. Run `bundle ex rake`.
2. Instead of success, we get the following three failures:
```
  1) Failure:
ArcGISClientTest#test_all [/Users/oblomov/Documents/code/covid-storepoint/test/unit/arcgis_client_test.rb:7]:
Expected nil (NilClass) to respond to #empty?.

  2) Error:
ArcGISClientTest#test_locations:
NoMethodError: undefined method `[]' for nil:NilClass
    /Users/oblomov/Documents/code/covid-storepoint/lib/test_sites/arcgis_client.rb:35:in `locations'
    /Users/oblomov/Documents/code/covid-storepoint/test/unit/arcgis_client_test.rb:11:in `test_locations'

  3) Error:
RakeTest#test_geocode_cac_locations:
NoMethodError: undefined method `[]' for nil:NilClass
    /Users/oblomov/Documents/code/covid-storepoint/lib/test_sites/arcgis_client.rb:35:in `locations'
    /Users/oblomov/Documents/code/covid-storepoint/lib/models/cac_location.rb:59:in `all_from_api'
    /Users/oblomov/Documents/code/covid-storepoint/Rakefile:38:in `block in <top (required)>'
    /Users/oblomov/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/rake-13.0.1/lib/rake/task.rb:281:in `block in execute'
    /Users/oblomov/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/rake-13.0.1/lib/rake/task.rb:281:in `each'
    /Users/oblomov/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/rake-13.0.1/lib/rake/task.rb:281:in `execute'
    /Users/oblomov/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/rake-13.0.1/lib/rake/task.rb:219:in `block in invoke_with_call_chain'
    /Users/oblomov/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/rake-13.0.1/lib/rake/task.rb:199:in `synchronize'
    /Users/oblomov/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/rake-13.0.1/lib/rake/task.rb:199:in `invoke_with_call_chain'
    /Users/oblomov/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/rake-13.0.1/lib/rake/task.rb:188:in `invoke'
    /Users/oblomov/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/rake-13.0.1/lib/rake/application.rb:160:in `invoke_task'
    /Users/oblomov/Documents/code/covid-storepoint/test/rake_test.rb:25:in `test_geocode_cac_locations'
```

## Questions

* Is this bug reproducible by engineering?
  - [x] yes
  - [ ] no

* What's the impact? All connections to the ArcGIS API fails.
  * Which users are affected? All
  * Does it happen all the time? Yes

**Comment by ivanoblomov** [comment]
@neilberkman not sure if they're doing maintenance or what but, unless I'm missing something, this effectively blocks all the `CAC-cutover-blocker` issues.

**Comment by neilberkman** [comment]
@ivanoblomov - can you check again? Working for me currently.

```
irb(main):003:0> TestSites::ArcGISClient.all
=> {"objectIdFieldName"=>"OBJECTID", "uniqueIdField"=>{"nam [...]
```

**Comment by ivanoblomov** [comment]
Dude, I don't doubt it. Chalk it off to my odd hours.

**Comment by ivanoblomov** [comment]
This appears to be a transient error, maybe due to maintenance or connectivity issues at the server, closing.
